################
#
#  Makefile for
#  I2c stuff
#  Author: Justin M. Bradley
#
################

OETMP = /home/quadrotor/overo-oe/tmp
STAGEDIR = ${OETMP}/sysroots/armv7a-angstrom-linux-gnueabi/usr
GUMLIB = ${STAGEDIR}/lib
GUMINC = ${STAGEDIR}/include

CC = gcc # Compile for Linux
CXX = g++ # Compile for Linux
GUMCC = $(OETMP)/sysroots/x86_64-linux/usr/armv7a/bin/arm-angstrom-linux-gnueabi-gcc
GUMCXX = $(OETMP)/sysroots/x86_64-linux/usr/armv7a/bin/arm-angstrom-linux-gnueabi-g++
CFLAGS = -W -O3 -Wall -Wextra -ansi -pedantic
GUMFLAGS = $(FLAGS) -I $(OETMP)/sysroots/overo-angstrom-linux-gnueabi/kernel/include/linux/i2c/ -L $(GUMLIB) -I $(GUMINC)
LD_FLAGS = -lrt -lm
INCLUDE = -I../include

O_FILES = Plan.o Control.o Comm.o Estimation.o Utilities.o simple_sock.o adc.o hc1_main.o
EXECUTABLE = ../hc1

I2C_O_FILES = i2c-api.o I2c_comm.o test_i2c.o
I2C_EXEC = ../i2c

SOCK_EXEC = ../sock
ADC_EXEC = ../adc
PWM_EXEC = ../pwm
COMM_EXEC = ../test_Comm

# Default make target is first
#
all:	$(O_FILES)
	$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $(EXECUTABLE) $(O_FILES) $(INCLUDE) $(LD_FLAGS)
	chmod 711 $(EXECUTABLE)

i2c:	$(I2C_O_FILES)
	$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $(I2C_EXEC) $(I2C_O_FILES) $(INCLUDE) $(LD_FLAGS)
	chmod 711 $(I2C_EXEC)

test_adc:	adc.o test_adc.c
		$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $(ADC_EXEC) test_adc.c adc.o $(INCLUDE) $(LD_FLAGS)
		chmod 711 $(ADC_EXEC)

test_pwm:	test_pwm.c ../include/pwm.h
		$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $(PWM_EXEC) test_pwm.c $(INCLUDE) $(LD_FLAGS)

test_server:	test_server.c simple_sock.c ../include/simple_sock.h
		$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $(SOCK_EXEC) test_server.c simple_sock.c $(INCLUDE) $(LD_FLAGS)
		chmod 711 $(SOCK_EXEC)

test_Comm:	./test_Comm.c ./Comm.c ../include/simple_sock.h ../include/Comm.h 
		$(CXX) $(CFLAGS) -o $(COMM_EXEC) test_Comm.c Comm.c simple_sock.c $(INCLUDE)
		chmod 711 $(COMM_EXEC)

test_i2c.o:	test_i2c.c
		$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $@ -c $< $(INCLUDE)

hc1_main.o:	hc1_main.c
		$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $@ -c $< $(INCLUDE)

%.o:	%.c ../include/%.h
	$(GUMCXX) $(CFLAGS) $(GUMFLAGS) -o $@ -c $< $(INCLUDE)

clean:
	rm -rf *.o $(EXECUTABLE) $(I2C_EXEC) $(SOCK_EXEC) $(ADC_EXEC) $(PWM_EXEC) $(COMM_EXEC)
